/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import clases.jugadores;
import java.awt.Color;
import javax.swing.JLabel;
import java.sql.SQLException;


/**
 *
 * @author Leidy
 */
public class diseño extends javax.swing.JFrame {

    
    JLabel modificar_tablero[] = new JLabel[18];
    
    jugadores modificar_jugador[] = new jugadores[3];
    
    int victoria[][]=
            
    {

            {1,2,3},
            {4,5,6},   
            {7,8,9},
            {10,11,12},
            {13,14,15},
            {16,17,18},
               ///////
            {1,4,7},
            {2,5,8},
            {3,6,9},
            {10,13,16},
            {11,14,17},
            {12,15,18},
            {4,7,10},
            {5,8,11},
            {6,9,12},
            {7,10,13},
            {8,11,14},
            {9,12,15},
            {10,13,16},
            {11,14,17},
            {12,15,18},
            
           /// Diagonales
            
            {1,5,9},
            {4,8,12},
            {7,11,15},
            {10,14,18},
            {3,5,7},
            {6,8,10},
            {9,11,13},
            {12,14,16},
         
            
            
            
    };                 
    
    jugadores jugador_1 = new jugadores();
    jugadores jugador_2 = new jugadores();
    jugadores jugador_3 = new jugadores();
           
   
    int turno=0;
    boolean estado=true;
    
 
    //BD
    
    BD  objeto_BD = new BD("juego");
    
    
    public diseño() {
        initComponents();
        
        objeto_BD.crear_tabla(objeto_BD.NOM_BD);
        
       this.setLocationRelativeTo(null);
        modificar_jugador[0]= jugador_1;
        modificar_jugador[1]=jugador_2;
        modificar_jugador[2]=jugador_3;
        
        modificar_tablero[0] = ca_1;
        modificar_tablero[1] = ca_2;
        modificar_tablero[2] = ca_3;
        modificar_tablero[3] = ca_4;
        modificar_tablero[4] = ca_5;
        modificar_tablero[5] = ca_6;
        modificar_tablero[6] = ca_7;
        modificar_tablero[7] = ca_8;
        modificar_tablero[8] = ca_9;
        modificar_tablero[9] = ca_10;
        modificar_tablero[10] = ca_11;
        modificar_tablero[11] = ca_12;
        modificar_tablero[12] = ca_13;
        modificar_tablero[13] = ca_14;
        modificar_tablero[14] = ca_15;
        modificar_tablero[15] = ca_16;
        modificar_tablero[16] = ca_17;
        modificar_tablero[17] = ca_18;
                   

        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_fondo = new javax.swing.JPanel();
        pnl_titulo = new javax.swing.JPanel();
        nombre_titulo = new javax.swing.JLabel();
        pnl_tablero = new javax.swing.JPanel();
        ca_1 = new javax.swing.JLabel();
        ca_2 = new javax.swing.JLabel();
        ca_3 = new javax.swing.JLabel();
        ca_4 = new javax.swing.JLabel();
        ca_5 = new javax.swing.JLabel();
        ca_6 = new javax.swing.JLabel();
        ca_7 = new javax.swing.JLabel();
        ca_8 = new javax.swing.JLabel();
        ca_9 = new javax.swing.JLabel();
        ca_10 = new javax.swing.JLabel();
        ca_11 = new javax.swing.JLabel();
        ca_12 = new javax.swing.JLabel();
        ca_13 = new javax.swing.JLabel();
        ca_14 = new javax.swing.JLabel();
        ca_15 = new javax.swing.JLabel();
        ca_16 = new javax.swing.JLabel();
        ca_17 = new javax.swing.JLabel();
        ca_18 = new javax.swing.JLabel();
        pnl_jugador = new javax.swing.JPanel();
        nombre_jugador = new javax.swing.JLabel();
        letra = new javax.swing.JLabel();
        Lab_nombre_jugador = new javax.swing.JLabel();
        lab_letra = new javax.swing.JLabel();
        boton_O = new javax.swing.JButton();
        boton_R = new javax.swing.JButton();
        boton_salir = new javax.swing.JButton();
        Boton_reiniciar = new javax.swing.JButton();
        anuncia_ganador = new javax.swing.JLabel();
        Btn_Historial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_fondo.setBackground(new java.awt.Color(204, 0, 204));

        pnl_titulo.setBackground(new java.awt.Color(255, 153, 255));

        nombre_titulo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        nombre_titulo.setText("ORO");

        javax.swing.GroupLayout pnl_tituloLayout = new javax.swing.GroupLayout(pnl_titulo);
        pnl_titulo.setLayout(pnl_tituloLayout);
        pnl_tituloLayout.setHorizontalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(nombre_titulo)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        pnl_tituloLayout.setVerticalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nombre_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_tablero.setBackground(new java.awt.Color(0, 0, 0));

        ca_1.setBackground(new java.awt.Color(255, 204, 204));
        ca_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_1.setOpaque(true);
        ca_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_1MouseClicked(evt);
            }
        });

        ca_2.setBackground(new java.awt.Color(255, 204, 204));
        ca_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_2.setOpaque(true);
        ca_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_2MouseClicked(evt);
            }
        });

        ca_3.setBackground(new java.awt.Color(255, 204, 204));
        ca_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_3.setOpaque(true);
        ca_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_3MouseClicked(evt);
            }
        });

        ca_4.setBackground(new java.awt.Color(255, 204, 204));
        ca_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_4.setOpaque(true);
        ca_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_4MouseClicked(evt);
            }
        });

        ca_5.setBackground(new java.awt.Color(255, 204, 204));
        ca_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_5.setOpaque(true);
        ca_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_5MouseClicked(evt);
            }
        });

        ca_6.setBackground(new java.awt.Color(255, 204, 204));
        ca_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_6.setOpaque(true);
        ca_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_6MouseClicked(evt);
            }
        });

        ca_7.setBackground(new java.awt.Color(255, 204, 204));
        ca_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_7.setOpaque(true);
        ca_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_7MouseClicked(evt);
            }
        });

        ca_8.setBackground(new java.awt.Color(255, 204, 204));
        ca_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_8.setOpaque(true);
        ca_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_8MouseClicked(evt);
            }
        });

        ca_9.setBackground(new java.awt.Color(255, 204, 204));
        ca_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_9.setOpaque(true);
        ca_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_9MouseClicked(evt);
            }
        });

        ca_10.setBackground(new java.awt.Color(255, 204, 204));
        ca_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_10.setOpaque(true);
        ca_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_10MouseClicked(evt);
            }
        });

        ca_11.setBackground(new java.awt.Color(255, 204, 204));
        ca_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_11.setOpaque(true);
        ca_11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_11MouseClicked(evt);
            }
        });

        ca_12.setBackground(new java.awt.Color(255, 204, 204));
        ca_12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_12.setOpaque(true);
        ca_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_12MouseClicked(evt);
            }
        });

        ca_13.setBackground(new java.awt.Color(255, 204, 204));
        ca_13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_13.setOpaque(true);
        ca_13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_13MouseClicked(evt);
            }
        });

        ca_14.setBackground(new java.awt.Color(255, 204, 204));
        ca_14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_14.setOpaque(true);
        ca_14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_14MouseClicked(evt);
            }
        });

        ca_15.setBackground(new java.awt.Color(255, 204, 204));
        ca_15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_15.setOpaque(true);
        ca_15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_15MouseClicked(evt);
            }
        });

        ca_16.setBackground(new java.awt.Color(255, 204, 204));
        ca_16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_16.setOpaque(true);
        ca_16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_16MouseClicked(evt);
            }
        });

        ca_17.setBackground(new java.awt.Color(255, 204, 204));
        ca_17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_17.setOpaque(true);
        ca_17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_17MouseClicked(evt);
            }
        });

        ca_18.setBackground(new java.awt.Color(255, 204, 204));
        ca_18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca_18.setOpaque(true);
        ca_18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca_18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_tableroLayout = new javax.swing.GroupLayout(pnl_tablero);
        pnl_tablero.setLayout(pnl_tableroLayout);
        pnl_tableroLayout.setHorizontalGroup(
            pnl_tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tableroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_tableroLayout.createSequentialGroup()
                        .addComponent(ca_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ca_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ca_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_tableroLayout.createSequentialGroup()
                        .addComponent(ca_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ca_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ca_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(245, 245, 245))
            .addGroup(pnl_tableroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_tableroLayout.createSequentialGroup()
                        .addComponent(ca_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ca_8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ca_9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_tableroLayout.createSequentialGroup()
                        .addComponent(ca_10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ca_11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ca_12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_tableroLayout.createSequentialGroup()
                        .addComponent(ca_13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ca_14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ca_15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_tableroLayout.createSequentialGroup()
                        .addComponent(ca_16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ca_17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ca_18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_tableroLayout.setVerticalGroup(
            pnl_tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tableroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ca_2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ca_1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ca_3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnl_tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ca_5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ca_4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ca_6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ca_8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ca_7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ca_9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnl_tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ca_11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ca_10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ca_12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ca_15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ca_14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ca_13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(pnl_tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ca_17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ca_16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ca_18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_jugador.setBackground(new java.awt.Color(255, 153, 153));

        nombre_jugador.setText("JUGADOR");

        letra.setText("LETRA");

        Lab_nombre_jugador.setText("nombre_jugador");

        lab_letra.setText("letra");

        javax.swing.GroupLayout pnl_jugadorLayout = new javax.swing.GroupLayout(pnl_jugador);
        pnl_jugador.setLayout(pnl_jugadorLayout);
        pnl_jugadorLayout.setHorizontalGroup(
            pnl_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_jugadorLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnl_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_jugadorLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(letra)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_letra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lab_nombre_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        pnl_jugadorLayout.setVerticalGroup(
            pnl_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_jugadorLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(pnl_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lab_nombre_jugador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra)
                    .addComponent(lab_letra))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        boton_O.setBackground(new java.awt.Color(255, 102, 255));
        boton_O.setText("O");
        boton_O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_OActionPerformed(evt);
            }
        });

        boton_R.setBackground(new java.awt.Color(255, 153, 255));
        boton_R.setText("R");
        boton_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_RActionPerformed(evt);
            }
        });

        boton_salir.setText("SALIR");
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });

        Boton_reiniciar.setText("REINICIAR");
        Boton_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_reiniciarActionPerformed(evt);
            }
        });

        anuncia_ganador.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        anuncia_ganador.setForeground(new java.awt.Color(51, 255, 0));
        anuncia_ganador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Btn_Historial.setText("Historial");
        Btn_Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_fondoLayout = new javax.swing.GroupLayout(pnl_fondo);
        pnl_fondo.setLayout(pnl_fondoLayout);
        pnl_fondoLayout.setHorizontalGroup(
            pnl_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_fondoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(pnl_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_fondoLayout.createSequentialGroup()
                        .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnl_fondoLayout.createSequentialGroup()
                        .addComponent(pnl_tablero, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnl_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_fondoLayout.createSequentialGroup()
                                .addGroup(pnl_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_fondoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pnl_jugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_fondoLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(boton_O, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(boton_R, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(66, 66, 66))
                            .addGroup(pnl_fondoLayout.createSequentialGroup()
                                .addGroup(pnl_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_fondoLayout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(boton_salir)
                                        .addGap(122, 122, 122)
                                        .addComponent(Boton_reiniciar))
                                    .addGroup(pnl_fondoLayout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(anuncia_ganador))
                                    .addGroup(pnl_fondoLayout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(Btn_Historial)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        pnl_fondoLayout.setVerticalGroup(
            pnl_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_fondoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_fondoLayout.createSequentialGroup()
                        .addComponent(pnl_tablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnl_fondoLayout.createSequentialGroup()
                        .addComponent(pnl_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(pnl_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_R, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_O, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pnl_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_salir)
                            .addComponent(Boton_reiniciar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Historial)
                        .addGap(24, 24, 24)
                        .addComponent(anuncia_ganador)
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_OActionPerformed
        modificar_jugador[turno].asignador_O();
        nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_boton_OActionPerformed

    private void ca_18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_18MouseClicked
        hacer_click(18);
        nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_18MouseClicked

    private void ca_17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_17MouseClicked
         hacer_click(17);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_17MouseClicked

    private void ca_16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_16MouseClicked
         hacer_click(16);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_16MouseClicked

    private void ca_15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_15MouseClicked
         hacer_click(15);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_15MouseClicked

    private void ca_14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_14MouseClicked
         hacer_click(14);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_14MouseClicked

    private void ca_13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_13MouseClicked
         hacer_click(13);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_13MouseClicked

    private void ca_12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_12MouseClicked
         hacer_click(12);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_12MouseClicked

    private void ca_11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_11MouseClicked
         hacer_click(11);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_11MouseClicked

    private void ca_10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_10MouseClicked
         hacer_click(10);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_10MouseClicked

    private void ca_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_9MouseClicked
         hacer_click(9);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_9MouseClicked

    private void ca_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_8MouseClicked
         hacer_click(8);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_8MouseClicked

    private void ca_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_7MouseClicked
         hacer_click(7);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_7MouseClicked

    private void ca_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_6MouseClicked
         hacer_click(6);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_6MouseClicked

    private void ca_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_5MouseClicked
         hacer_click(5);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_5MouseClicked

    private void ca_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_4MouseClicked
         hacer_click(4);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_4MouseClicked

    private void ca_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_3MouseClicked
         hacer_click(3);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_3MouseClicked

    private void ca_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_2MouseClicked
         hacer_click(2);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_2MouseClicked

    private void ca_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca_1MouseClicked
         hacer_click(1);
         nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_ca_1MouseClicked

    private void boton_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_RActionPerformed
        modificar_jugador[turno].asignador_R();
        nombre_seleccionado();
        letra_seleccionada();
    }//GEN-LAST:event_boton_RActionPerformed

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        objeto_BD.borrar_tablas(objeto_BD.NOM_BD);
        System.exit(0);
        
    }//GEN-LAST:event_boton_salirActionPerformed

    private void Boton_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_reiniciarActionPerformed
        reiniciar();
    }//GEN-LAST:event_Boton_reiniciarActionPerformed

    private void Btn_HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HistorialActionPerformed
               
   objeto_BD.setVisible(true);
   objeto_BD.contar();
               
    }//GEN-LAST:event_Btn_HistorialActionPerformed
    
    
    
    
    public void hacer_click(int casilla){
        
    if (modificar_tablero[casilla-1].getText()==("")&& estado== true){
        
        modificar_tablero[casilla-1].setText(modificar_jugador[turno].letra);
        
    if (turno==0){
         modificar_tablero[casilla-1].setForeground(jugador_1.color_selecionado);
        
    }
    else {
      if (turno==1){
         modificar_tablero[casilla-1].setForeground(jugador_2.color_selecionado);
        
    }
    else {
      if (turno==2){
         modificar_tablero[casilla-1].setForeground(jugador_3.color_selecionado);
    
    
    }
    }
    }
        turno_jugador(casilla);
        victoria(casilla);
    }
    }
    
    public void turno_jugador(int casilla){
     if (turno==0) {
     turno=1;
    
     }
     else {
      if (turno==1) {
     turno=2;
     }    
       
      else {
      if (turno==2) {
     turno=0;
    }

      }
     }
    }
    
        
  public void nombre_seleccionado(){
      Lab_nombre_jugador.setText(modificar_jugador[turno].nombre);
  }      
        
 public void letra_seleccionada(){
     lab_letra.setText(modificar_jugador[turno].letra);
 }
 
 
 /// cambiar turno
 public void victoria(int casilla){
   for (int i=0; i<victoria.length;i++) {
   /// victoria primer jugador 
       if (modificar_tablero[victoria[i][0] - 1].getText() == ("O") && modificar_tablero[victoria[i][0] - 1].getForeground() == (jugador_1.color_selecionado)
               && modificar_tablero[victoria[i][1] - 1].getText() == ("R") && modificar_tablero[victoria[i][1] - 1].getForeground() == (jugador_1.color_selecionado)
               && modificar_tablero[victoria[i][2] - 1].getText() == ("O") && modificar_tablero[victoria[i][2] - 1].getForeground() == (jugador_1.color_selecionado)
   )
           
               {
                 modificar_tablero[victoria[i][0]-1].setBackground(Color.WHITE);
                 modificar_tablero[victoria[i][1]-1].setBackground(Color.WHITE);
                 modificar_tablero[victoria[i][2]-1].setBackground(Color.WHITE);
                 anuncia_ganador.setText("LA VICTORIA ES PARA " + jugador_1.nombre);
                 
                 
               objeto_BD.insertar(objeto_BD.NOM_BD, jugador_1.nombre);
                 
                 
                 
                 estado=false;
                 
                 
                 
                 
                 
                 
                 
               }  else
       
   if (modificar_tablero[victoria[i][0] - 1].getText() == ("O") && modificar_tablero[victoria[i][0] - 1].getForeground() == (jugador_2.color_selecionado)
               && modificar_tablero[victoria[i][1] - 1].getText() == ("R") && modificar_tablero[victoria[i][1] - 1].getForeground() == (jugador_2.color_selecionado)
               && modificar_tablero[victoria[i][2] - 1].getText() == ("O") && modificar_tablero[victoria[i][2] - 1].getForeground() == (jugador_2.color_selecionado)
   )
           
               {
                 modificar_tablero[victoria[i][0]-1].setBackground(Color.WHITE);
                 modificar_tablero[victoria[i][1]-1].setBackground(Color.WHITE);
                 modificar_tablero[victoria[i][2]-1].setBackground(Color.WHITE);
                 anuncia_ganador.setText("LA VICTORIA ES PARA " + jugador_2.nombre);
                 
                 
               objeto_BD.insertar(objeto_BD.NOM_BD, jugador_2.nombre);
                    
                 
                 
                 
                 estado=false;
                 
                 
                 
                 
                 
               }    else
       
   if (modificar_tablero[victoria[i][0] - 1].getText() == ("O") && modificar_tablero[victoria[i][0] - 1].getForeground() == (jugador_3.color_selecionado)
               && modificar_tablero[victoria[i][1] - 1].getText() == ("R") && modificar_tablero[victoria[i][1] - 1].getForeground() == (jugador_3.color_selecionado)
               && modificar_tablero[victoria[i][2] - 1].getText() == ("O") && modificar_tablero[victoria[i][2] - 1].getForeground() == (jugador_3.color_selecionado)
   )
           
               {
                 modificar_tablero[victoria[i][0]-1].setBackground(Color.WHITE);
                 modificar_tablero[victoria[i][1]-1].setBackground(Color.WHITE);
                 modificar_tablero[victoria[i][2]-1].setBackground(Color.WHITE);
                 anuncia_ganador.setText("LA VICTORIA ES PARA " + jugador_3.nombre);
                 
                 
                 
                  objeto_BD.insertar(objeto_BD.NOM_BD, jugador_3.nombre);
                 
                 estado=false;
                 
                 
               }
   
   
   
   }
   
 
           
 }
  
     public void reiniciar(){
     
         for (int i =0; i<modificar_tablero.length; i++){
           modificar_tablero[i].setText("");
           modificar_tablero[i].setBackground(Color.CYAN);
             
         }
         turno=0;
         Lab_nombre_jugador.setText("");
         lab_letra.setText("");
         anuncia_ganador.setText("");
         estado=true;
         
         }
             
         
     
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diseño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_reiniciar;
    private javax.swing.JButton Btn_Historial;
    private javax.swing.JLabel Lab_nombre_jugador;
    private javax.swing.JLabel anuncia_ganador;
    private javax.swing.JButton boton_O;
    private javax.swing.JButton boton_R;
    private javax.swing.JButton boton_salir;
    private javax.swing.JLabel ca_1;
    private javax.swing.JLabel ca_10;
    private javax.swing.JLabel ca_11;
    private javax.swing.JLabel ca_12;
    private javax.swing.JLabel ca_13;
    private javax.swing.JLabel ca_14;
    private javax.swing.JLabel ca_15;
    private javax.swing.JLabel ca_16;
    private javax.swing.JLabel ca_17;
    private javax.swing.JLabel ca_18;
    private javax.swing.JLabel ca_2;
    private javax.swing.JLabel ca_3;
    private javax.swing.JLabel ca_4;
    private javax.swing.JLabel ca_5;
    private javax.swing.JLabel ca_6;
    private javax.swing.JLabel ca_7;
    private javax.swing.JLabel ca_8;
    private javax.swing.JLabel ca_9;
    private javax.swing.JLabel lab_letra;
    private javax.swing.JLabel letra;
    private javax.swing.JLabel nombre_jugador;
    private javax.swing.JLabel nombre_titulo;
    private javax.swing.JPanel pnl_fondo;
    private javax.swing.JPanel pnl_jugador;
    private javax.swing.JPanel pnl_tablero;
    private javax.swing.JPanel pnl_titulo;
    // End of variables declaration//GEN-END:variables
}
